name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - name: Install
        run: pnpm install
      - name: Run tests
        run: pnpm test
